### CHAPTER - 1 : Modular Programming in Python

## Funtion

In [1]:
# print simple hello world with the help of functon
def Hello_world():
    print('hello world')

Hello_world()

hello world


### Default Arguments / Keyword Arguments

In [2]:
# Default arguments are those arguments which can be changed but their value remains the same if not given.
# An example of the same is given below.
def double_the_no(num=3):
    return num * 2

double_the_no()
    

6

## Positional Arguments 

In [5]:
def double_the_no(num):
    return num * 2

print(double_the_no(2))

4


## Lambda 

In [6]:
# Write function for square of number
def square(num):
    result = num ** 2
    return result

square(4)

16

In [9]:
# Now square of number with lambda function
square_of_number = lambda X: X**2
square_of_number(5)

25

In [10]:
addition = lambda a,b: a + b
addition (2,4)

6

## Map

In [14]:
#  map(function, sequence)
list_1 = [1, 4, 9, 16]
square_no = map(square, list_1)
print(square_no)


## Object Oriented Programming 

In [15]:
print(type(1))
print(type([]))

<class 'int'>
<class 'list'>


### Class

In [17]:
# Create new object type called sample
class Sample(object):
    pass

x = Sample()

print(type(x))

<class '__main__.Sample'>


In [25]:
# Attributes 
# Creating Dog class
class Dog(object):
    def __init__(self, name):
        self.name = name
        
# Create instance of dog class
dog_1 = Dog('Puppy')
dog_1.name        


'Puppy'

## Methods

In [42]:
class Circle(object):
    pi = 3.14
    
    def __init__(self, radius=5):
        self.radius = radius
        
    # This method calculate the area 
    def area(self):
        return self.radius * self.radius * Circle.pi
    
    # Method for resetting radius
    def set_radius(self , radius):
        return self.radius
        
    # Method for getting radius
    def get_radius(self):
        return self.radius

# Create Instance of Circle class
c = Circle()

# Call the methods
print(c.set_radius(5))
print(c.area())
print(c.get_radius())



5
78.5
5


## Instance vs Class vs Static Methods

In [50]:
class Myclass():
    def instance_method(self):
        print("This is Instance method")
        
    @classmethod
    def class_method(cls):
        print('Class Method Called')
    
    @staticmethod
    def static_method():
        print('static method call')
        
obj = Myclass()

obj.instance_method()
obj.class_method()
obj.static_method()

        

This is Instance method
Class Method Called
static method call


##  Mini Challange 1

In [55]:
# write a function square_root having default value of input a=9 and find the square-root of the same
 
def square_root(a = 9):
    result = a**0.5
    return int(result)
square_root()

3

## Mini Challange 2

In [57]:
# write a function function_tuple that takes in two numbers a and b and 
# returns the sum as well as the product of these numbers

def function_tuple(a, b):
    sum = a + b
    product = a *b
    return sum , product

function_tuple(4,5)

(9, 20)

In [62]:
# mini challange 2 with oops

class SumProduct():
    def __init__(self, a, b):
        self.a = a
        self.b = b
        
    def addition(self):
        return self.a + self.b
    
    def product(self):
        return self.a * self.b
    
obj = SumProduct(4,8)
print(obj.addition())
print(obj.product())

12
32


## Mini Challange 3

In [59]:
# write lambda function to add two numbers
sum = lambda x,y: x+y
sum(10)

40

## CHAPTER - 2 : NumPy

### ndarray

In [64]:
import numpy as np
my_list = [10,20,30,40]
np.array(my_list)

array([10, 20, 30, 40])

In [65]:
# list to 2d array
my_list_1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list_1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
type(np.array(my_list_1))

numpy.ndarray

#### dtype and Shape

In [68]:
my_lists =[[1,2,3,4,5],[2,4,52,3,5]]
arr = np.array(my_lists)
print(arr.dtype)
print(arr.shape)

int32
(2, 5)


### NumPy Built-in methods

In [71]:
# arange
import numpy as np
a = np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [72]:
# zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
# ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
# Eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
np.eye(1)

array([[1.]])

In [76]:
# linspace
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [81]:
np.linspace(1,100,3)

array([  1. ,  50.5, 100. ])

In [82]:
# rand
np.random.rand(3,4)

array([[0.28239546, 0.44477894, 0.82076962, 0.4850588 ],
       [0.11400246, 0.17373897, 0.12104181, 0.31318515],
       [0.61499675, 0.4994283 , 0.33104381, 0.9385663 ]])

In [83]:
# randn
np.random.randn(3,4)

array([[-1.64423390e-03,  7.62992917e-02, -3.84289924e-01,
        -4.61578445e-01],
       [ 8.65301535e-01,  3.20708447e-01, -5.08361955e-01,
         1.72968582e+00],
       [-7.25225952e-01,  4.00978546e-01,  1.57457903e+00,
         6.79285392e-01]])

In [84]:
# randint
np.random.randint(4,40,10)

array([20, 33, 24,  6, 13, 17,  8,  7, 19, 24])