## Week 3

### Numpy Advanced & Intro to pandas

### Indexing and Selection

In [2]:
import numpy as np
arr = np.arange(10)
print('Array', arr)

# Get 6th element of array
print(arr[7])

# get value in range
print(arr[0:10:2])

Array [0 1 2 3 4 5 6 7 8 9]
7
[0 2 4 6 8]


In [ ]:
# indexing two dimensional array
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print()
print(arr1[2])
print(arr1[1][1])
print(arr1[2,2])

### Use of Filter

In [4]:
arr2 = np.array([[2,3,4],[5,7,8],[9,2,1]])
below5_filter = (arr2 < 5)
print(below5_filter)
                

[[ True  True  True]
 [False False False]
 [False  True  True]]


In [5]:
arr2[below5_filter]

array([2, 3, 4, 2, 1])

### Replacing Values

In [6]:
import numpy as np

vector = np.array([10,4,20,30,4])
equal_to_ten_or_greater = (vector == 10) | (vector > 10)
vector[equal_to_ten_or_greater] = 100
print(vector)

[100   4 100 100   4]


## Mini Challange - 1

In [7]:
# Locate the number 5 in below array
#arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4[1][1])

5


## Mini Challange - 2

In [12]:
# Can you print the first two rows of the array arr. 
# Also note that you only have to print the first three columns.

arr5 = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11,12,13,14,15]])
print(arr5[0:2,0:3])


[[1 2 3]
 [6 7 8]]


## Introduction to Pandas

### Series

In [18]:
# Creating pandas series from list
import pandas as pd
my_list = [2,5,4,6,7]
series = pd.Series(data = my_list)

print(series)
print(series.index)
print(series.values)


0    2
1    5
2    4
3    6
4    7
dtype: int64
RangeIndex(start=0, stop=5, step=1)
[2 5 4 6 7]


In [17]:
# Create series from numpy array
import numpy as np
arr6 = np.array([10,20,30])
index = ['a','b','c']

pd.Series(data = arr6, index = index)

a    10
b    20
c    30
dtype: int32

In [19]:
# Create series from dictionary
import pandas as pd
import numpy as np

d = {'a':'sunil', 'b':'Anil', 'c':'Ram'}
pd.Series(d)

a    sunil
b     Anil
c      Ram
dtype: object

## Mini Challange - 3

In [20]:
# Find the value of 'USSR' from the series ser1
import pandas as pd
ser1 = pd.Series([1,2,3,4], index=['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4], index=['USA', 'Germany','Italy', 'Japan'])

print(ser1['USSR'])

3
